### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by panmyuan** [JXingZhao/EGNet#11]
为什么测试的时候，图片不保存呢？
![GK{QL61WGRAD%}AE6)486)Y](https://user-images.githubusercontent.com/48192787/65565373-4ea9bc80-df82-11e9-9632-98ad26e865c4.png)
对应目录里没有图片

**Comment by panmyuan** [comment]
> 为什么测试的时候，图片不保存呢？
> ![GK{QL61WGRAD%}AE6)486)Y](https://user-images.githubusercontent.com/48192787/65565373-4ea9bc80-df82-11e9-9632-98ad26e865c4.png)
> 对应目录里没有图片

**Comment by JXingZhao** [comment]
你可以把保存的路径输出下，一般这种情况就是路径不对，输出到了一个不存在的目录下。






发件人：panmyuan <notifications@github.com>
发送日期：2019-09-25 12:09:16
收件人：JXingZhao/EGNet <EGNet@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：Re: [JXingZhao/EGNet] 测试问题 (#11)
为什么测试的时候，图片不保存呢？

 对应目录里没有图片
